# Change these first
owner: d-michal # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Sčitanie 2021
    url: https://gis.scitanie.sk/portal/apps/sites/#/obyvatelia
  - name: Sčitanie 2021 - Server Health
    url: https://gis.scitanie.sk/server/rest/info/healthcheck?f=pjson
    __dangerous__body_down_if_text_missing: '"success": true'
  - name: Sčitanie 2021 - DB Query
    url: https://gis.scitanie.sk/server/rest/services/Hosted/obyv_roz_hustota_pocet/FeatureServer/9/query?where=1%3D1&outFields=spolu&f=json
    __dangerous__body_down_if_text_missing: '"spolu":5449270'
  - name: Územná príprava Sčitanie 2021
    url: https://censusup.statistics.sk/portal/home/
  - name: Mapy CDB
    url: https://ismcs.cdb.sk/mapviewer
  - name: MULP
    url: https://mulp.nlcsk.org/webgiseditor
  - name: Portál MULP
    url: https://mulp.nlcsk.org/portal/home/
  - name: Portál NLCSK
    url: https://gis.nlcsk.org/portal/home/
    
status-website:
  theme: dark
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: https://d-michal.github.io/upptime/
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
